/* Generated by Yosys 0.64+68 (git sha1 413169663, clang++ 18.1.8 -fPIC -O3) */

module Top(clk, reset, start, A_in, B_in, opcode, result_out, carry, zero_flag, overflow_flag, done);
  input clk;
  wire clk;
  input reset;
  wire reset;
  input start;
  wire start;
  input [7:0] A_in;
  wire [7:0] A_in;
  input [7:0] B_in;
  wire [7:0] B_in;
  input [2:0] opcode;
  wire [2:0] opcode;
  output [7:0] result_out;
  wire [7:0] result_out;
  output carry;
  wire carry;
  output zero_flag;
  wire zero_flag;
  output overflow_flag;
  wire overflow_flag;
  output done;
  wire done;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire [7:0] A_out;
  wire [7:0] B_out;
  wire [2:0] alu_opcode;
  wire [7:0] \alu_unit.A ;
  wire [7:0] \alu_unit.B ;
  wire [2:0] \alu_unit.alu_opcode ;
  wire \alu_unit.carry ;
  wire \alu_unit.overflow_flag ;
  wire \alu_unit.zero_flag ;
  wire [2:0] \cu_unit.alu_opcode ;
  wire \cu_unit.clk ;
  wire \cu_unit.done ;
  wire [1:0] \cu_unit.next_state ;
  wire [2:0] \cu_unit.opcode ;
  wire \cu_unit.reset ;
  wire \cu_unit.start ;
  wire [1:0] \cu_unit.state ;
  wire [7:0] \reg_unit.A_in ;
  wire [7:0] \reg_unit.A_out ;
  wire [7:0] \reg_unit.B_in ;
  wire [7:0] \reg_unit.B_out ;
  wire \reg_unit.clk ;
  wire \reg_unit.reset ;
  wire [7:0] \reg_unit.result_out ;
  sky130_fd_sc_hd__clkinv_1 _179_ (
    .A(\reg_unit.A_out [1]),
    .Y(_050_)
  );
  sky130_fd_sc_hd__clkinv_1 _180_ (
    .A(\reg_unit.A_out [2]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__clkinv_1 _181_ (
    .A(\reg_unit.A_out [3]),
    .Y(_052_)
  );
  sky130_fd_sc_hd__clkinv_1 _182_ (
    .A(\reg_unit.A_out [4]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__clkinv_1 _183_ (
    .A(\reg_unit.A_out [5]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__clkinv_1 _184_ (
    .A(\reg_unit.A_out [6]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__clkinv_1 _185_ (
    .A(reset),
    .Y(_012_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _186_ (
    .A(\cu_unit.state [0]),
    .SLEEP(\cu_unit.state [1]),
    .X(_056_)
  );
  sky130_fd_sc_hd__mux2_1 _187_ (
    .A0(\reg_unit.B_out [7]),
    .A1(B_in[7]),
    .S(_056_),
    .X(_035_)
  );
  sky130_fd_sc_hd__mux2_1 _188_ (
    .A0(\reg_unit.A_out [7]),
    .A1(A_in[7]),
    .S(_056_),
    .X(_034_)
  );
  sky130_fd_sc_hd__and2_0 _189_ (
    .A(\cu_unit.state [0]),
    .B(\cu_unit.state [1]),
    .X(_057_)
  );
  sky130_fd_sc_hd__nand2_1 _190_ (
    .A(\cu_unit.state [0]),
    .B(\cu_unit.state [1]),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nor2_1 _191_ (
    .A(opcode[1]),
    .B(opcode[2]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__and2_0 _192_ (
    .A(opcode[0]),
    .B(_059_),
    .X(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _193_ (
    .A(opcode[0]),
    .B(_059_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nor2_1 _194_ (
    .A(\reg_unit.B_out [7]),
    .B(\reg_unit.A_out [7]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nand2_1 _195_ (
    .A(\reg_unit.B_out [7]),
    .B(\reg_unit.A_out [7]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nor2b_1 _196_ (
    .A(_062_),
    .B_N(_063_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand2_1 _197_ (
    .A(\reg_unit.B_out [6]),
    .B(\reg_unit.A_out [6]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nor2_1 _198_ (
    .A(\reg_unit.B_out [6]),
    .B(\reg_unit.A_out [6]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _199_ (
    .A(_065_),
    .SLEEP(_066_),
    .X(_067_)
  );
  sky130_fd_sc_hd__nor2_1 _200_ (
    .A(\reg_unit.B_out [5]),
    .B(\reg_unit.A_out [5]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__xnor2_1 _201_ (
    .A(\reg_unit.B_out [5]),
    .B(\reg_unit.A_out [5]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nor2_1 _202_ (
    .A(\reg_unit.B_out [4]),
    .B(\reg_unit.A_out [4]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _203_ (
    .A(\reg_unit.B_out [4]),
    .SLEEP(\reg_unit.A_out [4]),
    .X(_071_)
  );
  sky130_fd_sc_hd__nand2_1 _204_ (
    .A(\reg_unit.B_out [4]),
    .B(\reg_unit.A_out [4]),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand2_1 _205_ (
    .A(_071_),
    .B(_072_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nor2_1 _206_ (
    .A(\reg_unit.B_out [3]),
    .B(\reg_unit.A_out [3]),
    .Y(_074_)
  );
  sky130_fd_sc_hd__xor2_1 _207_ (
    .A(\reg_unit.B_out [3]),
    .B(\reg_unit.A_out [3]),
    .X(_075_)
  );
  sky130_fd_sc_hd__nor2_1 _208_ (
    .A(\reg_unit.B_out [2]),
    .B(\reg_unit.A_out [2]),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nand2_1 _209_ (
    .A(\reg_unit.B_out [2]),
    .B(\reg_unit.A_out [2]),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nor2b_1 _210_ (
    .A(_076_),
    .B_N(_077_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nor2_1 _211_ (
    .A(\reg_unit.B_out [1]),
    .B(\reg_unit.A_out [1]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nand2_1 _212_ (
    .A(\reg_unit.B_out [1]),
    .B(\reg_unit.A_out [1]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nand2b_1 _213_ (
    .A_N(_079_),
    .B(_080_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nand2_1 _214_ (
    .A(\reg_unit.B_out [0]),
    .B(\reg_unit.A_out [0]),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nor2_1 _215_ (
    .A(\reg_unit.B_out [0]),
    .B(\reg_unit.A_out [0]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _216_ (
    .A(_082_),
    .SLEEP(_083_),
    .X(_084_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _217_ (
    .A(\reg_unit.B_out [0]),
    .SLEEP(\reg_unit.A_out [0]),
    .X(_085_)
  );
  sky130_fd_sc_hd__maj3_1 _218_ (
    .A(\reg_unit.B_out [1]),
    .B(_050_),
    .C(_085_),
    .X(_086_)
  );
  sky130_fd_sc_hd__maj3_1 _219_ (
    .A(\reg_unit.B_out [2]),
    .B(_051_),
    .C(_086_),
    .X(_087_)
  );
  sky130_fd_sc_hd__maj3_1 _220_ (
    .A(\reg_unit.B_out [3]),
    .B(_052_),
    .C(_087_),
    .X(_088_)
  );
  sky130_fd_sc_hd__maj3_1 _221_ (
    .A(\reg_unit.B_out [4]),
    .B(_053_),
    .C(_088_),
    .X(_089_)
  );
  sky130_fd_sc_hd__maj3_1 _222_ (
    .A(\reg_unit.B_out [5]),
    .B(_054_),
    .C(_089_),
    .X(_090_)
  );
  sky130_fd_sc_hd__maj3_1 _223_ (
    .A(\reg_unit.B_out [6]),
    .B(_055_),
    .C(_090_),
    .X(_091_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _224_ (
    .A(\reg_unit.B_out [7]),
    .SLEEP(\reg_unit.A_out [7]),
    .X(_092_)
  );
  sky130_fd_sc_hd__nand2b_1 _225_ (
    .A_N(\reg_unit.B_out [7]),
    .B(\reg_unit.A_out [7]),
    .Y(_093_)
  );
  sky130_fd_sc_hd__xnor2_1 _226_ (
    .A(_064_),
    .B(_091_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__a21oi_1 _227_ (
    .A1(_080_),
    .A2(_082_),
    .B1(_079_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand2_1 _228_ (
    .A(_078_),
    .B(_095_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__a22oi_1 _229_ (
    .A1(\reg_unit.B_out [2]),
    .A2(\reg_unit.A_out [2]),
    .B1(\reg_unit.A_out [3]),
    .B2(\reg_unit.B_out [3]),
    .Y(_097_)
  );
  sky130_fd_sc_hd__a21oi_1 _230_ (
    .A1(_096_),
    .A2(_097_),
    .B1(_074_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nand3_1 _231_ (
    .A(_071_),
    .B(_072_),
    .C(_098_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__a22oi_1 _232_ (
    .A1(\reg_unit.B_out [4]),
    .A2(\reg_unit.A_out [4]),
    .B1(\reg_unit.A_out [5]),
    .B2(\reg_unit.B_out [5]),
    .Y(_100_)
  );
  sky130_fd_sc_hd__a21oi_1 _233_ (
    .A1(_099_),
    .A2(_100_),
    .B1(_068_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__a21boi_0 _234_ (
    .A1(_067_),
    .A2(_101_),
    .B1_N(_065_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__xor2_1 _235_ (
    .A(_064_),
    .B(_102_),
    .X(_103_)
  );
  sky130_fd_sc_hd__nor3_1 _236_ (
    .A(opcode[1]),
    .B(opcode[0]),
    .C(opcode[2]),
    .Y(_104_)
  );
  sky130_fd_sc_hd__or3_1 _237_ (
    .A(opcode[1]),
    .B(opcode[0]),
    .C(opcode[2]),
    .X(_105_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _238_ (
    .A(opcode[1]),
    .SLEEP(opcode[2]),
    .X(_106_)
  );
  sky130_fd_sc_hd__nand2_1 _239_ (
    .A(opcode[0]),
    .B(_106_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _240_ (
    .A(_106_),
    .SLEEP(opcode[0]),
    .X(_108_)
  );
  sky130_fd_sc_hd__nand2b_1 _241_ (
    .A_N(opcode[0]),
    .B(_106_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__o22ai_1 _242_ (
    .A1(_103_),
    .A2(_105_),
    .B1(_107_),
    .B2(_062_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__o221ai_1 _243_ (
    .A1(_061_),
    .A2(_094_),
    .B1(_109_),
    .B2(_063_),
    .C1(_057_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__o22a_1 _244_ (
    .A1(\reg_unit.result_out [7]),
    .A2(_057_),
    .B1(_110_),
    .B2(_111_),
    .X(_033_)
  );
  sky130_fd_sc_hd__mux2_1 _245_ (
    .A0(\reg_unit.B_out [0]),
    .A1(B_in[0]),
    .S(_056_),
    .X(_032_)
  );
  sky130_fd_sc_hd__mux2_1 _246_ (
    .A0(\reg_unit.B_out [1]),
    .A1(B_in[1]),
    .S(_056_),
    .X(_031_)
  );
  sky130_fd_sc_hd__mux2_1 _247_ (
    .A0(\reg_unit.B_out [2]),
    .A1(B_in[2]),
    .S(_056_),
    .X(_030_)
  );
  sky130_fd_sc_hd__mux2_1 _248_ (
    .A0(\reg_unit.B_out [3]),
    .A1(B_in[3]),
    .S(_056_),
    .X(_029_)
  );
  sky130_fd_sc_hd__mux2_1 _249_ (
    .A0(\reg_unit.B_out [4]),
    .A1(B_in[4]),
    .S(_056_),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux2_1 _250_ (
    .A0(\reg_unit.B_out [5]),
    .A1(B_in[5]),
    .S(_056_),
    .X(_027_)
  );
  sky130_fd_sc_hd__mux2_1 _251_ (
    .A0(\reg_unit.B_out [6]),
    .A1(B_in[6]),
    .S(_056_),
    .X(_026_)
  );
  sky130_fd_sc_hd__mux2_1 _252_ (
    .A0(\reg_unit.A_out [0]),
    .A1(A_in[0]),
    .S(_056_),
    .X(_049_)
  );
  sky130_fd_sc_hd__nand2_1 _253_ (
    .A(A_in[1]),
    .B(_056_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__o21ai_0 _254_ (
    .A1(_050_),
    .A2(_056_),
    .B1(_112_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand2_1 _255_ (
    .A(A_in[2]),
    .B(_056_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__o21ai_0 _256_ (
    .A1(_051_),
    .A2(_056_),
    .B1(_113_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nand2_1 _257_ (
    .A(A_in[3]),
    .B(_056_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__o21ai_0 _258_ (
    .A1(_052_),
    .A2(_056_),
    .B1(_114_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nand2_1 _259_ (
    .A(A_in[4]),
    .B(_056_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__o21ai_0 _260_ (
    .A1(_053_),
    .A2(_056_),
    .B1(_115_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand2_1 _261_ (
    .A(A_in[5]),
    .B(_056_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__o21ai_0 _262_ (
    .A1(_054_),
    .A2(_056_),
    .B1(_116_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nand2_1 _263_ (
    .A(A_in[6]),
    .B(_056_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__o21ai_0 _264_ (
    .A1(_055_),
    .A2(_056_),
    .B1(_117_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__o22ai_1 _265_ (
    .A1(_083_),
    .A2(_107_),
    .B1(_109_),
    .B2(_082_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__a21oi_1 _266_ (
    .A1(_059_),
    .A2(_084_),
    .B1(_118_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nand2_1 _267_ (
    .A(\reg_unit.result_out [0]),
    .B(_058_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__o21ai_0 _268_ (
    .A1(_058_),
    .A2(_119_),
    .B1(_120_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__xnor2_1 _269_ (
    .A(_081_),
    .B(_085_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__xnor2_1 _270_ (
    .A(_081_),
    .B(_082_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__nor2_1 _271_ (
    .A(_105_),
    .B(_122_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__o22ai_1 _272_ (
    .A1(_079_),
    .A2(_107_),
    .B1(_109_),
    .B2(_080_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__a211oi_1 _273_ (
    .A1(_060_),
    .A2(_121_),
    .B1(_123_),
    .C1(_124_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nand2_1 _274_ (
    .A(\reg_unit.result_out [1]),
    .B(_058_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__o21ai_0 _275_ (
    .A1(_058_),
    .A2(_125_),
    .B1(_126_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__xnor2_1 _276_ (
    .A(_078_),
    .B(_086_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__nor2_1 _277_ (
    .A(_061_),
    .B(_127_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__xnor2_1 _278_ (
    .A(_078_),
    .B(_095_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__o22ai_1 _279_ (
    .A1(_076_),
    .A2(_107_),
    .B1(_109_),
    .B2(_077_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__o21ai_0 _280_ (
    .A1(_105_),
    .A2(_129_),
    .B1(_057_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__o32a_1 _281_ (
    .A1(_128_),
    .A2(_130_),
    .A3(_131_),
    .B1(_057_),
    .B2(\reg_unit.result_out [2]),
    .X(_040_)
  );
  sky130_fd_sc_hd__xnor2_1 _282_ (
    .A(_075_),
    .B(_087_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nand2_1 _283_ (
    .A(_077_),
    .B(_096_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__xor2_1 _284_ (
    .A(_075_),
    .B(_133_),
    .X(_134_)
  );
  sky130_fd_sc_hd__nand2_1 _285_ (
    .A(_104_),
    .B(_134_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__o21ai_0 _286_ (
    .A1(_074_),
    .A2(_107_),
    .B1(_135_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__a31oi_1 _287_ (
    .A1(\reg_unit.B_out [3]),
    .A2(\reg_unit.A_out [3]),
    .A3(_108_),
    .B1(_058_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__o21ai_0 _288_ (
    .A1(_061_),
    .A2(_132_),
    .B1(_137_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__o22a_1 _289_ (
    .A1(\reg_unit.result_out [3]),
    .A2(_057_),
    .B1(_136_),
    .B2(_138_),
    .X(_039_)
  );
  sky130_fd_sc_hd__nor2_1 _290_ (
    .A(\reg_unit.result_out [4]),
    .B(_057_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__xor2_1 _291_ (
    .A(_073_),
    .B(_088_),
    .X(_140_)
  );
  sky130_fd_sc_hd__nor2_1 _292_ (
    .A(_061_),
    .B(_140_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__xnor2_1 _293_ (
    .A(_073_),
    .B(_098_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nand2_1 _294_ (
    .A(opcode[0]),
    .B(_071_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__nand2_1 _295_ (
    .A(_072_),
    .B(_143_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__a221oi_1 _296_ (
    .A1(_104_),
    .A2(_142_),
    .B1(_144_),
    .B2(_106_),
    .C1(_141_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__a21oi_1 _297_ (
    .A1(_057_),
    .A2(_145_),
    .B1(_139_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__xor2_1 _298_ (
    .A(_069_),
    .B(_089_),
    .X(_146_)
  );
  sky130_fd_sc_hd__nand2_1 _299_ (
    .A(_072_),
    .B(_099_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__xnor2_1 _300_ (
    .A(_069_),
    .B(_147_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__a31oi_1 _301_ (
    .A1(\reg_unit.B_out [5]),
    .A2(\reg_unit.A_out [5]),
    .A3(_108_),
    .B1(_058_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__o21ai_0 _302_ (
    .A1(_068_),
    .A2(_107_),
    .B1(_149_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__a21oi_1 _303_ (
    .A1(_104_),
    .A2(_148_),
    .B1(_150_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__o21ai_0 _304_ (
    .A1(_061_),
    .A2(_146_),
    .B1(_151_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__o21a_1 _305_ (
    .A1(\reg_unit.result_out [5]),
    .A2(_057_),
    .B1(_152_),
    .X(_037_)
  );
  sky130_fd_sc_hd__nor2_1 _306_ (
    .A(\reg_unit.result_out [6]),
    .B(_057_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__xor2_1 _307_ (
    .A(_067_),
    .B(_090_),
    .X(_154_)
  );
  sky130_fd_sc_hd__xor2_1 _308_ (
    .A(_067_),
    .B(_101_),
    .X(_155_)
  );
  sky130_fd_sc_hd__nor2_1 _309_ (
    .A(_065_),
    .B(_109_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__o21ai_0 _310_ (
    .A1(_066_),
    .A2(_107_),
    .B1(_057_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__a21oi_1 _311_ (
    .A1(_104_),
    .A2(_155_),
    .B1(_156_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__a21oi_1 _312_ (
    .A1(_060_),
    .A2(_154_),
    .B1(_157_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__a21oi_1 _313_ (
    .A1(_158_),
    .A2(_159_),
    .B1(_153_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nor2_1 _314_ (
    .A(start),
    .B(\cu_unit.state [1]),
    .Y(_160_)
  );
  sky130_fd_sc_hd__nor2_1 _315_ (
    .A(\cu_unit.state [0]),
    .B(_160_),
    .Y(\cu_unit.next_state [0])
  );
  sky130_fd_sc_hd__a21boi_0 _316_ (
    .A1(_064_),
    .A2(_102_),
    .B1_N(_063_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__nor2b_1 _317_ (
    .A(_091_),
    .B_N(_093_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__o32ai_1 _318_ (
    .A1(_061_),
    .A2(_092_),
    .A3(_162_),
    .B1(_161_),
    .B2(_105_),
    .Y(carry)
  );
  sky130_fd_sc_hd__a21oi_1 _319_ (
    .A1(_063_),
    .A2(_102_),
    .B1(_105_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__o21ai_0 _320_ (
    .A1(_062_),
    .A2(_102_),
    .B1(_163_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__a21oi_1 _321_ (
    .A1(_091_),
    .A2(_093_),
    .B1(_061_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__o21ai_0 _322_ (
    .A1(_091_),
    .A2(_092_),
    .B1(_165_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__nand2_1 _323_ (
    .A(_164_),
    .B(_166_),
    .Y(overflow_flag)
  );
  sky130_fd_sc_hd__nand2_1 _324_ (
    .A(_122_),
    .B(_129_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__nor3_1 _325_ (
    .A(_084_),
    .B(_105_),
    .C(_167_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__nor4_1 _326_ (
    .A(_134_),
    .B(_142_),
    .C(_148_),
    .D(_155_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__nand3_1 _327_ (
    .A(_103_),
    .B(_168_),
    .C(_169_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__and4_1 _328_ (
    .A(_063_),
    .B(_065_),
    .C(_080_),
    .D(_082_),
    .X(_171_)
  );
  sky130_fd_sc_hd__nand4_1 _329_ (
    .A(_074_),
    .B(_076_),
    .C(_079_),
    .D(_083_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__nand4_1 _330_ (
    .A(_062_),
    .B(_066_),
    .C(_068_),
    .D(_070_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__nor3_1 _331_ (
    .A(_107_),
    .B(_172_),
    .C(_173_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__a41oi_1 _332_ (
    .A1(_097_),
    .A2(_100_),
    .A3(_108_),
    .A4(_171_),
    .B1(_174_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__nand4_1 _333_ (
    .A(_081_),
    .B(_132_),
    .C(_140_),
    .D(_146_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__nor4_1 _334_ (
    .A(_061_),
    .B(_084_),
    .C(_154_),
    .D(_176_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__nand3_1 _335_ (
    .A(_094_),
    .B(_127_),
    .C(_177_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__nand3_1 _336_ (
    .A(_170_),
    .B(_175_),
    .C(_178_),
    .Y(zero_flag)
  );
  sky130_fd_sc_hd__xor2_1 _337_ (
    .A(\cu_unit.state [0]),
    .B(\cu_unit.state [1]),
    .X(\cu_unit.next_state [1])
  );
  sky130_fd_sc_hd__nor2_1 _338_ (
    .A(\cu_unit.state [0]),
    .B(\cu_unit.state [1]),
    .Y(done)
  );
  sky130_fd_sc_hd__clkinv_1 _339_ (
    .A(reset),
    .Y(_013_)
  );
  sky130_fd_sc_hd__clkinv_1 _340_ (
    .A(reset),
    .Y(_014_)
  );
  sky130_fd_sc_hd__clkinv_1 _341_ (
    .A(reset),
    .Y(_015_)
  );
  sky130_fd_sc_hd__clkinv_1 _342_ (
    .A(reset),
    .Y(_016_)
  );
  sky130_fd_sc_hd__clkinv_1 _343_ (
    .A(reset),
    .Y(_017_)
  );
  sky130_fd_sc_hd__clkinv_1 _344_ (
    .A(reset),
    .Y(_018_)
  );
  sky130_fd_sc_hd__clkinv_1 _345_ (
    .A(reset),
    .Y(_019_)
  );
  sky130_fd_sc_hd__clkinv_1 _346_ (
    .A(reset),
    .Y(_020_)
  );
  sky130_fd_sc_hd__clkinv_1 _347_ (
    .A(reset),
    .Y(_021_)
  );
  sky130_fd_sc_hd__clkinv_1 _348_ (
    .A(reset),
    .Y(_022_)
  );
  sky130_fd_sc_hd__clkinv_1 _349_ (
    .A(reset),
    .Y(_023_)
  );
  sky130_fd_sc_hd__clkinv_1 _350_ (
    .A(reset),
    .Y(_024_)
  );
  sky130_fd_sc_hd__clkinv_1 _351_ (
    .A(reset),
    .Y(_025_)
  );
  sky130_fd_sc_hd__clkinv_1 _352_ (
    .A(reset),
    .Y(_000_)
  );
  sky130_fd_sc_hd__clkinv_1 _353_ (
    .A(reset),
    .Y(_001_)
  );
  sky130_fd_sc_hd__clkinv_1 _354_ (
    .A(reset),
    .Y(_002_)
  );
  sky130_fd_sc_hd__clkinv_1 _355_ (
    .A(reset),
    .Y(_003_)
  );
  sky130_fd_sc_hd__clkinv_1 _356_ (
    .A(reset),
    .Y(_004_)
  );
  sky130_fd_sc_hd__clkinv_1 _357_ (
    .A(reset),
    .Y(_005_)
  );
  sky130_fd_sc_hd__clkinv_1 _358_ (
    .A(reset),
    .Y(_006_)
  );
  sky130_fd_sc_hd__clkinv_1 _359_ (
    .A(reset),
    .Y(_007_)
  );
  sky130_fd_sc_hd__clkinv_1 _360_ (
    .A(reset),
    .Y(_008_)
  );
  sky130_fd_sc_hd__clkinv_1 _361_ (
    .A(reset),
    .Y(_009_)
  );
  sky130_fd_sc_hd__clkinv_1 _362_ (
    .A(reset),
    .Y(_010_)
  );
  sky130_fd_sc_hd__clkinv_1 _363_ (
    .A(reset),
    .Y(_011_)
  );
  sky130_fd_sc_hd__dfrtp_1 _364_ (
    .CLK(clk),
    .D(_032_),
    .Q(\reg_unit.B_out [0]),
    .RESET_B(_007_)
  );
  sky130_fd_sc_hd__dfrtp_1 _365_ (
    .CLK(clk),
    .D(_031_),
    .Q(\reg_unit.B_out [1]),
    .RESET_B(_006_)
  );
  sky130_fd_sc_hd__dfrtp_1 _366_ (
    .CLK(clk),
    .D(_030_),
    .Q(\reg_unit.B_out [2]),
    .RESET_B(_005_)
  );
  sky130_fd_sc_hd__dfrtp_1 _367_ (
    .CLK(clk),
    .D(_029_),
    .Q(\reg_unit.B_out [3]),
    .RESET_B(_004_)
  );
  sky130_fd_sc_hd__dfrtp_1 _368_ (
    .CLK(clk),
    .D(_028_),
    .Q(\reg_unit.B_out [4]),
    .RESET_B(_003_)
  );
  sky130_fd_sc_hd__dfrtp_1 _369_ (
    .CLK(clk),
    .D(_027_),
    .Q(\reg_unit.B_out [5]),
    .RESET_B(_002_)
  );
  sky130_fd_sc_hd__dfrtp_1 _370_ (
    .CLK(clk),
    .D(_026_),
    .Q(\reg_unit.B_out [6]),
    .RESET_B(_001_)
  );
  sky130_fd_sc_hd__dfrtp_1 _371_ (
    .CLK(clk),
    .D(_035_),
    .Q(\reg_unit.B_out [7]),
    .RESET_B(_011_)
  );
  sky130_fd_sc_hd__dfrtp_1 _372_ (
    .CLK(clk),
    .D(_049_),
    .Q(\reg_unit.A_out [0]),
    .RESET_B(_000_)
  );
  sky130_fd_sc_hd__dfrtp_1 _373_ (
    .CLK(clk),
    .D(_048_),
    .Q(\reg_unit.A_out [1]),
    .RESET_B(_025_)
  );
  sky130_fd_sc_hd__dfrtp_1 _374_ (
    .CLK(clk),
    .D(_047_),
    .Q(\reg_unit.A_out [2]),
    .RESET_B(_024_)
  );
  sky130_fd_sc_hd__dfrtp_1 _375_ (
    .CLK(clk),
    .D(_046_),
    .Q(\reg_unit.A_out [3]),
    .RESET_B(_023_)
  );
  sky130_fd_sc_hd__dfrtp_1 _376_ (
    .CLK(clk),
    .D(_045_),
    .Q(\reg_unit.A_out [4]),
    .RESET_B(_022_)
  );
  sky130_fd_sc_hd__dfrtp_1 _377_ (
    .CLK(clk),
    .D(_044_),
    .Q(\reg_unit.A_out [5]),
    .RESET_B(_021_)
  );
  sky130_fd_sc_hd__dfrtp_1 _378_ (
    .CLK(clk),
    .D(_043_),
    .Q(\reg_unit.A_out [6]),
    .RESET_B(_020_)
  );
  sky130_fd_sc_hd__dfrtp_1 _379_ (
    .CLK(clk),
    .D(_034_),
    .Q(\reg_unit.A_out [7]),
    .RESET_B(_009_)
  );
  sky130_fd_sc_hd__dfrtp_1 _380_ (
    .CLK(clk),
    .D(_042_),
    .Q(\reg_unit.result_out [0]),
    .RESET_B(_019_)
  );
  sky130_fd_sc_hd__dfrtp_1 _381_ (
    .CLK(clk),
    .D(_041_),
    .Q(\reg_unit.result_out [1]),
    .RESET_B(_018_)
  );
  sky130_fd_sc_hd__dfrtp_1 _382_ (
    .CLK(clk),
    .D(_040_),
    .Q(\reg_unit.result_out [2]),
    .RESET_B(_017_)
  );
  sky130_fd_sc_hd__dfrtp_1 _383_ (
    .CLK(clk),
    .D(_039_),
    .Q(\reg_unit.result_out [3]),
    .RESET_B(_016_)
  );
  sky130_fd_sc_hd__dfrtp_1 _384_ (
    .CLK(clk),
    .D(_038_),
    .Q(\reg_unit.result_out [4]),
    .RESET_B(_015_)
  );
  sky130_fd_sc_hd__dfrtp_1 _385_ (
    .CLK(clk),
    .D(_037_),
    .Q(\reg_unit.result_out [5]),
    .RESET_B(_014_)
  );
  sky130_fd_sc_hd__dfrtp_1 _386_ (
    .CLK(clk),
    .D(_036_),
    .Q(\reg_unit.result_out [6]),
    .RESET_B(_013_)
  );
  sky130_fd_sc_hd__dfrtp_1 _387_ (
    .CLK(clk),
    .D(_033_),
    .Q(\reg_unit.result_out [7]),
    .RESET_B(_008_)
  );
  sky130_fd_sc_hd__dfrtp_1 _388_ (
    .CLK(clk),
    .D(\cu_unit.next_state [0]),
    .Q(\cu_unit.state [0]),
    .RESET_B(_012_)
  );
  sky130_fd_sc_hd__dfrtp_1 _389_ (
    .CLK(clk),
    .D(\cu_unit.next_state [1]),
    .Q(\cu_unit.state [1]),
    .RESET_B(_010_)
  );
  assign \cu_unit.clk  = clk;
  assign \cu_unit.done  = done;
  assign \cu_unit.alu_opcode  = opcode;
  assign \cu_unit.reset  = reset;
  assign \alu_unit.overflow_flag  = overflow_flag;
  assign \cu_unit.opcode  = opcode;
  assign \cu_unit.start  = start;
  assign \alu_unit.zero_flag  = zero_flag;
  assign \alu_unit.carry  = carry;
  assign \reg_unit.reset  = reset;
  assign \reg_unit.clk  = clk;
  assign \reg_unit.B_in  = B_in;
  assign \reg_unit.A_in  = A_in;
  assign \alu_unit.alu_opcode  = opcode;
  assign \alu_unit.B  = \reg_unit.B_out ;
  assign \alu_unit.A  = \reg_unit.A_out ;
  assign B_out = \reg_unit.B_out ;
  assign A_out = \reg_unit.A_out ;
  assign alu_opcode = opcode;
  assign result_out = \reg_unit.result_out ;
endmodule
